### ISSUE TITLE
Press release is a dead link

### ISSUE THREAD

**Issue by jcrben** [benschwarz/developers.whatwg.org#105]
The [press release](http://archive.germanforblack.com/articles/html5-for-web-developers#_=_) link is dead. I really think the press release content should be moved into the repository. Given that it is described as the document on the "conception, construction and future" of the project, it should probably be kept up to date and version controlled.

**Comment by domenic** [comment]
(I already said this in #115, but I will repeat it here since this was the original issue.)

We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback). It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

The new version does not have a press release link, at least for now. Adding some sort of introduction is tracked by https://github.com/whatwg/html/issues/2780; probably we will link to both the original press release, [via archive.org](http://web.archive.org/web/20150220020906/http://archive.germanforblack.com:80/articles/html5-for-web-developers#_=_), and the blog post announcing the revamp.

So, let me close this in favor of that tracking issue over on whatwg/html.
