### ISSUE TITLE
Google fonts still loaded over http instead of https causing warning

### ISSUE THREAD

**Issue by Janghou** [benschwarz/developers.whatwg.org#108]
On https://developers.whatwg.org/ Google fonts are loaded over http, causing a insecure blocked content error in Opera.
<link href="http://fonts.googleapis.com/css?family=Droid+Serif:regular,italic,bold" rel="stylesheet">

Is this commit by Paul Irish somehow not merged?
https://github.com/benschwarz/developers.whatwg.org/commit/562a0af900ff605fd1e5467ef172c8061dedcd42
Or is the site not updated afterwards...

**Comment by benschwarz** [comment]
This'll be covered by #107

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

In the new version, we are hosting the fonts locally. This was because one of our contributors noted that Google Fonts is blocked in China. So, this problem is now fixed, in a different way :).
