### ISSUE TITLE
Mashup with WhenCanIUse type data?

### ISSUE THREAD

**Issue by AFBarstow** [benschwarz/developers.whatwg.org#53]
This isn't an Issue but rather an enhancement request -> to include a link to deployment data (e.g. WhenCanIUse.com) so it would be relatively easy for an author to determine the deployment status for those features in the spec that have some (credible and reliable) deployment data.

**Comment by domenic** [comment]
Good news! We've [revamped the developer's edition](https://blog.whatwg.org/developers-edition-comeback) and now it syncs automatically with the source spec. It's at a new URL, https://html.spec.whatwg.org/dev/. (We are working to set up a redirect.)

Amusingly, in the time between when this issue was filed and now, the main spec at https://html.spec.whatwg.org/multipage/ has gained its own caniuse boxes.

As such, I've moved this issue to https://github.com/whatwg/html/issues/2794, and re-titled it "Output caniuse boxes in the dev edition as well".
